using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace StatDNS
{
    /// <remarks>https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml</remarks>
    [JsonConverter(typeof (StringEnumConverter))]
    public enum StatDNSType
    {
        A,
        A6,
        AAAA,
        AFSDB,
        APL,
        ATMA,
        AXFR,
        CAA,
        CDNSKEY,
        CDS,
        CERT,
        CNAME,
        DHCID,
        DLV,
        DNAME,
        DNSKEY,
        DS,
        EID,
        EUI48,
        EUI64,
        GID,
        GPOS,
        HINFO,
        HIP,
        IPSECKEY,
        ISDN,
        IXFR,
        KEY,
        KX,
        L32,
        L64,
        LOC,
        LP,
        MAILA,
        MAILB,
        MB,
        MD,
        MF,
        MG,
        MINFO,
        MR,
        MX,
        NAPTR,
        NID,
        NIMLOC,
        NINFO,
        NS,
        NSAP,
        [EnumMember(Value = "NSAP-PTR")] NSAPPTR,
        NSEC,
        NSEC3,
        NSEC3PARAM,
        NULL,
        NXT,
        OPENPGPKEY,
        OPT,
        PTR,
        PX,
        RKEY,
        RP,
        RRSIG,
        RT,
        SIG,
        SINK,
        SOA,
        SPF,
        SRV,
        SSHFP,
        TA,
        TALINK,
        TKEY,
        TLSA,
        TSIG,
        TXT,
        UID,
        UINFO,
        UNSPEC,
        URI,
        WKS,
        X25,
    }
}